apiVersion: v1
kind: Service
metadata:
  name: control-tower
  namespace: default
spec:
    ports:
    - nodePort: 30000
      port: 2015
      protocol: TCP
      targetPort: 2015
    selector:
      name: control-tower
    type: NodePort
